apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ownership-service-policy
  namespace: scm
spec:
  podSelector:
    matchLabels:
      app: ownership-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app: fabric-peer
      ports:
        - protocol: TCP
          port: 7051